## PHASE - II

1. file handling and data processing with files

In [2]:
data = open('data.txt','r')
print(data.read())


hbsxlhjabc akuijn'o


In [ ]:
data = 

2. List and Dictionary comprehenssion

In [1]:
li = [i for i in range(1,10)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
li = [i*i for i in range(1,10)]
li

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
n = 5
li = [[n,i,n*i] for i in range(1,11)]
li

[[5, 1, 5],
 [5, 2, 10],
 [5, 3, 15],
 [5, 4, 20],
 [5, 5, 25],
 [5, 6, 30],
 [5, 7, 35],
 [5, 8, 40],
 [5, 9, 45],
 [5, 10, 50]]

In [1]:
s = input()
capital = [i.lower() for i in s]
capital

ABCD


['a', 'b', 'c', 'd']

In [2]:
s = input()
capital = [i.swapcase() for i in s]
capital

shudcHUJBFCF


['S', 'H', 'U', 'D', 'C', 'h', 'u', 'j', 'b', 'f', 'c', 'f']

In [4]:
s = input()
digits = [i for i in s if i.isdigit()]
digits

ghjkl34567hjk76t5rewbn 345


['3', '4', '5', '6', '7', '7', '6', '5', '3', '4', '5']

In [5]:
letters = list(map(lambda x: x, 'human'))
print(letters)

['h', 'u', 'm', 'a', 'n']


In [8]:
s = "ARCHANA"
l = list(map(lambda x:x+'a',s))
l




['Aa', 'Ra', 'Ca', 'Ha', 'Aa', 'Na', 'Aa']

3. Iterators and Generators

In [ ]:
Ambika

4. maps and filters

In [10]:
n = input()
n

123


'123'

In [12]:
n = int(n)
n

123

In [14]:
n = input().split()
res = list(map(int,n))
res

1 2 3 4 5


[1, 2, 3, 4, 5]

In [15]:
n = input().split()
res = list(map(float,n))
res

1 2 3 45 6 5 3 33 3 2 4


[1.0, 2.0, 3.0, 45.0, 6.0, 5.0, 3.0, 33.0, 3.0, 2.0, 4.0]

In [23]:
#n = [1,2,3,4,5,6]
def even(n):
    if n%2 == 0:
        return "even"
    return "odd"
li = map(even,[2,3,4,5,6])
print(list(li))
    

['even', 'odd', 'even', 'odd', 'even']


In [25]:
def addition(n):
    return n+n
    
li = map(addition,[2,3,4,5,6])
print(list(li))

[4, 6, 8, 10, 12]


In [26]:
n = (1,5,4,5)
lambda1 = map(lambda x:x+x,n)
print(list(lambda1))

[2, 10, 8, 10]


In [28]:
n1 = [4,5,6,7]
n2 = [7,7,8,5]

test = map(lambda x,y:x*y,n1,n2)
print(list(test))

[28, 35, 48, 35]


In [30]:
l = "anu"
str1 = map(list,l)
print(list(str1))

[['a'], ['n'], ['u']]


In [34]:
str2 = input().split()
def length(n):
    return len(n)
#len1 = map(length,['anu','archana','chinnu'])
len1 = map(length,str2)
print(list(len1))

archana anu
[7, 3]


## 5. Numpy
    - NumPy Introduction:
        * NumPy stands for numeric python 
        * which is a python package for the computation and processing of the multidimensional and single dimensional array elements.
        * Travis Oliphant created NumPy package in 2005
#### Use of Numpy
    1. NumPy performs array-oriented computing.
    2. It efficiently implements the multidimensional arrays.
    3. It performs scientific computations.
  

In [15]:
import numpy as n
data = n.array([[2,3,4,5,5],[4,5,6,7,8]])
print(data,"\n item size is",data.itemsize,"bytes")   # for finding item size
print(data.size)                                      # for finding size
print(data.shape)                                     # for finding the shape of the matrix

[[2 3 4 5 5]
 [4 5 6 7 8]] 
 item size is 4 bytes
10
(2, 5)


In [18]:
n1 = list(map(int,input().split()))
n2 = list(map(int,input().split()))
data1 = n.array([n1,n2])
data1

1 2 3
2 3 4


array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
res = data1.reshape(3,2)
res

array([[1, 2],
       [3, 2],
       [3, 4]])

In [24]:
ran = n.arange(0,50)
print(ran)
ran = ran.reshape(5,10)
ran

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
ran1 = n.random.randint(1,50,size=(5,3))
print("original matrix is:  \n",ran1)
result = ran1.reshape(3,5)
result


original matrix is:  
 [[ 7 41 36]
 [47  3 44]
 [ 6 24 35]
 [22  8 32]
 [37 30 28]]


array([[ 7, 41, 36, 47,  3],
       [44,  6, 24, 35, 22],
       [ 8, 32, 37, 30, 28]])

In [35]:
print(result.max())
print(result.min())
print("sum is:",result.sum())
print("mean is: ",result.mean())
print("standard deviation is: ",result.std())

47
3
sum is: 400
mean is:  26.666666666666668
standard deviation is:  14.083875729200239


In [37]:
zeros = n.zeros((5,5))
print("original matrix is:\n",zeros)

original matrix is:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [50]:
zeros1 = n.zeros((4,5),int)
print("with integer values is:\n",zeros1)

with integer values is:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [51]:
ones = n.ones((5,6))
print("original matrix is: \n",ones)

original matrix is: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [53]:
ones1 = n.ones((5,6),int)
print("with integer values: \n",ones1)

with integer values: 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
