# 1)program to changing order of index of given series

In [4]:
import pandas as pd
names=["satheesh","prasanna","ravi","Avinash","Archana"]
index=[1,2,3,4,5]
a=pd.Series(names,index)
a=a.reindex(index=[4,5,3,2,1])# order of index changing
a

4     Avinash
5     Archana
3        ravi
2    prasanna
1    satheesh
dtype: object

# 2)program to add substract,divide of two pandas series

In [5]:
import pandas as pd
a=[2,4,6,8,10]
b=[1,3,5,7,9]
# addition
data=pd.Series(a)
data2=pd.Series(b)
sum1=data+data2
sub=data-data2
divide=data/data2
print("sum is",sum1)
print("substration is",sub)
print("division is",divide)


sum is 0     3
1     7
2    11
3    15
4    19
dtype: int64
substration is 0    1
1    1
2    1
3    1
4    1
dtype: int64
division is 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# 3)convert pandas module series into python list

In [9]:
import pandas as pd
a=[1,2,3]
x=pd.Series(a)
x=x.tolist()
print(x)
type(x)

[1, 2, 3]


list

# 4)program to select the rows whare the score is NaN?

In [38]:
examdata= {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

data=pd.DataFrame(examdata , index=labels)
print(data[data['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


# 5)print today date

In [15]:
import pandas as pd
from datetime import date
today_date=pd.to_datetime(str(date.today()))
print(today_date)

2019-12-07 00:00:00


# 6) create pivot table by considering titanic

In [40]:
import pandas as pd
import numpy as np
titanic=pd.read_csv('titanic.csv')# csv file in my folder
titanic_tbl=pd.pivot_table(titanic,index=['Name','Age'])
titanic_tbl

Fare  Parch  \
Name                                         Age                    
Abbing, Mr. Anthony                          42.0   7.5500      0   
Abbott, Mr. Rossmore Edward                  16.0  20.2500      1   
Abbott, Mrs. Stanton (Rosa Hunt)             35.0  20.2500      1   
Abelson, Mr. Samuel                          30.0  24.0000      0   
Abelson, Mrs. Samuel (Hannah Wizosky)        28.0  24.0000      0   
...                                                    ...    ...   
de Messemaeker, Mrs. Guillaume Joseph (Emma) 36.0  17.4000      0   
de Mulder, Mr. Theodore                      30.0   9.5000      0   
de Pelsmaeker, Mr. Alfons                    16.0   9.5000      0   
del Carlo, Mr. Sebastiano                    29.0  27.7208      0   
van Billiard, Mr. Austin Blyler              40.5  14.5000      2   

                                                   PassengerId  Pclass  SibSp  \
Name                                         Age                                
Abbing, Mr. Anthony                          42.0          846       3      0   
Abbott, Mr. Rossmore Edward                  16.0          747       3      1   
Abbott, Mrs. Stanton (Rosa Hunt)             35.0          280       3      1   
Abelson, Mr. Samuel                          30.0          309       2      1   
Abelson, Mrs. Samuel (Hannah Wizosky)        28.0          875       2      1   
...                                                        ...     ...    ...   
de Messemaeker, Mrs. Guillaume Joseph (Emma) 36.0          560       3      1   
de Mulder, Mr. Theodore                      30.0          287       3      0   
de Pelsmaeker, Mr. Alfons                    16.0          283       3      0   
del Carlo, Mr. Sebastiano                    29.0          362       2      1   
van Billiard, Mr. Austin Blyler              40.5          154       3      0   

                                                   Survived  
Name                                         Age             
Abbing, Mr. Anthony                          42.0         0  
Abbott, Mr. Rossmore Edward                  16.0         0  
Abbott, Mrs. Stanton (Rosa Hunt)             35.0         1  
Abelson, Mr. Samuel                          30.0         0  
Abelson, Mrs. Samuel (Hannah Wizosky)        28.0         1  
...                                                     ...  
de Messemaeker, Mrs. Guillaume Joseph (Emma) 36.0         1  
de Mulder, Mr. Theodore                      30.0         1  
de Pelsmaeker, Mr. Alfons                    16.0         0  
del Carlo, Mr. Sebastiano                    29.0         0  
van Billiard, Mr. Austin Blyler              40.5         0  

[714 rows x 6 columns]

# 7)program 3X3 matrix with range 2,10

In [22]:
import numpy as np
st=int(input())
ed=int(input())
a=np.arange(st,ed).reshape(3,3)
a

2
11


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 8) programto illustrate diff between revel and flatten by tlking multidimensional array?

In [28]:
import numpy as np
x=np.array(((1,2,3),(4,5,6),(7,8,9)))
print(x.ravel())
print(x.flatten())
# flatten returns a new array(copy array)
# ravel sometimes returns same array(view of array)


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# 9)program to create numpy array and fining min,max,and indices and statistical methods

In [36]:
import numpy as np
x=np.random.random((3,4))
print(x)
mini=x.min()
print("minimum",mini)
maxi=x.max()
print("maximum",maxi)
print("indics",x[:,:3])

[[0.33771082 0.77432316 0.06936581 0.9837693 ]
 [0.82005012 0.82717833 0.80268164 0.9148309 ]
 [0.35640116 0.3182811  0.15620812 0.022522  ]]
minimum 0.02252200225230372
maximum 0.9837692966262822
indics [[0.33771082 0.77432316 0.06936581]
 [0.82005012 0.82717833 0.80268164]
 [0.35640116 0.3182811  0.15620812]]
